### PR TITLE
Create Engineering Standards doc (mostly empty)

### PR DESCRIPTION
**Pull request by karlmdavis**
**JIRA Ticket:**
N/A (we don't currently have a Jira project for this kind of DASG admin work)

**User Story or Bug Summary:**

As a DASG staffer, I need a document to place Engineering Standards in, so that we can start formally discussing and defining them (via the usual GitHub PR process).

### What Does This PR Do?

Create Engineering Standards doc (mostly empty).

Doesn't have any actual standards yet, but creates a place to land them,
in separate PRs.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

* Does this adequately and reasonably explain why we're creating standards?

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies? **No**.
    * Does this PR modify or invalidate any of our security controls? **No**.
    * Does this PR store or transmit data that was not stored or transmitted before? **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **No**.

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following pre-requisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ ] **N/A**: I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by dhgreene — APPROVED** [review]
🏁

**Review by DeirdreHolub — COMMENTED** [review]
I think it is important to discuss in this document how we will know we've succeeded in achieving these goals. Or put another way, how are we measuring results? Does reduce duplicate work mean sharing code or replacing code? does it also mean reducing cognitive load on team members? As an example, I might think it's a win on all goals to build a standalone executable service that does `Thing A`, where the service can be used by any program, even one built on top of a different language. You might think eew, more network connections! centralize all the Things! Like all contrived examples, this one is simplified, and intended to illuminate my point.

**Comment by karlmdavis** [comment]
> I think it is important to discuss in this document how we will know we've succeeded in achieving these goals. Or put another way, how are we measuring results? Does reduce duplicate work mean sharing code or replacing code? does it also mean reducing cognitive load on team members? As an example, I might think it's a win on all goals to build a standalone executable service that does `Thing A`, where the service can be used by any program, even one built on top of a different language. You might think eew, more network connections! centralize all the Things! Like all contrived examples, this one is simplified, and intended to illuminate my point.

@DeirdreHolub All great questions, but I think they need to be answered in the context of the specific requirements they relate to, not in the goals sections. If you look at the earlier draft PR (#2), you'll see that each specific standard has an evaluation section, which is intended to address that.

Does that approach address your concern sufficiently? (Leaving aside the specific standards and criteria there, which aren't up for review here -- just does the _approach_ work?)

**Comment by karlmdavis** [comment]
Alright, calling the play out loud here, for transparency: I’m going to merge this PR with only one approved review, as I’ve been unable to get sufficient review attention on it.

If you decide you have questions or concerns later, let me know — this is pretty much just documentation and can be easily changed or improved, if needed.

**Pull request merged**
